version: '3.1'

services:
 rrtb-bot:
   depends_on:
     - rrtb-db
   build:
     context: .
   environment:
     BOT_NAME: ${BOT_NAME}
     BOT_TOKEN: ${BOT_TOKEN}
     ADMINS: ${ADMINS}
     BOT_DB_USERNAME: ${BOT_DB_USERNAME}
     BOT_DB_PASSWORD: ${BOT_DB_PASSWORD}
   restart: always
 rrtb-db:
   hostname: rrtb-db-prod
   image: postgres:15.2-bullseye
   restart: always
   environment:
     POSTGRES_DB: 'rrtb_db'
     POSTGRES_USER: ${BOT_DB_USERNAME}
     POSTGRES_PASSWORD: ${BOT_DB_PASSWORD}
   ports:
     - '5432:5432'
   expose:
     - '5432'
